name: Publish new version of the web

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Push to external repository
        env:
          EXTERNAL_REPO_URL: ${{ secrets.BLUEBOARD_REPO_URL }}
        run: |
          if [[ $EXTERNAL_REPO_URL == git@* ]]; then
            # Setup SSH
            mkdir -p ~/.ssh
            echo "${{ secrets.BLUEBOARD_GITHUB_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan $(echo $EXTERNAL_REPO_URL | cut -d@ -f2 | cut -d: -f1) >> ~/.ssh/known_hosts
          fi

          # Add external repository as remote and push
          git remote add external $EXTERNAL_REPO_URL
          git push external master:production --force
